version: "3.7"
# docker engine 18.03.0+

# Сборка и запуск Nginx для обновления сертификатов

services:
    
  # Nginx reverse proxy
  proxy:
    container_name: proxy
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./production:/etc/nginx/conf.d
      - ./production/certbot/conf:/etc/letsencrypt
      - ./production/certbot/www:/var/www/certbot
    networks:
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # Автообновление сертификатов Let's Encrypt
  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: always
    volumes:
      - ./production/certbot/conf:/etc/letsencrypt
      - ./production/certbot/www:/var/www/certbot
    networks:
      - web
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    
networks:
  web:
    external: false
    name: web